services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
